name: NewsApp
description: News content.
version: 1.0.0+1

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

enable-web: true

dependencies:
  flutter:
    sdk: flutter
  firebase_auth: ^0.8.1
  google_sign_in: ^4.0.1
  flutter_google_places: ^0.1.4+1
  cloud_firestore: ^0.9.0+1
  firebase_core: ^0.3.0+1
  firebase_storage: ^2.0.1
  font_awesome_flutter: ^8.0.1
  country_code_picker: ^1.1.0
  cupertino_icons: ^0.1.2
  http: ^0.11.3+14
  flutter_webview_plugin: 0.3.3
  image_picker: ^0.4.6
  cached_network_image: ^0.4.1
  fluttertoast: ^2.0.7
  shared_preferences: ^0.4.3
  event_bus: ^1.0.1
  barcode_scan: ^0.0.4
  geolocator: ^2.1.1
  location: ^1.1.6
  uuid: ^1.0.3
  auto_size_text: 0.3.0
  dio: ^3.0.7
  intl: ^0.15.7

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

assets:
  # config
  - config/channel.json
  # images
  - images/ic_avatar_default.png
  - images/ic_nav_news_normal.png
  - images/ic_nav_news_actived.png
  - images/ic_nav_tweet_normal.png
  - images/ic_nav_tweet_actived.png
  - images/ic_nav_discover_normal.png
  - images/ic_nav_discover_actived.png
  - images/ic_nav_my_normal.png
  - images/ic_nav_my_pressed.png
  - images/ic_discover_gist.png
  - images/ic_discover_git.png
  - images/ic_discover_nearby.png
  - images/ic_discover_pos.png
  - images/ic_discover_scan.png
  - images/ic_discover_shake.png
  - images/ic_discover_softwares.png
  - images/ic_arrow_right.png
  - images/ic_my_blog.png
  - images/ic_my_message.png
  - images/ic_my_question.png
  - images/ic_my_recommend.png
  - images/ic_my_team.png
  - images/ic_test.png
  - images/ic_hongshu.jpg
  - images/ic_img_default.jpg
  - images/ic_comment.png
  - images/cover_img.jpg
  - images/leftmenu/ic_xiaoheiwu.png
  - images/leftmenu/ic_fabu.png
  - images/leftmenu/ic_about.png
  - images/leftmenu/ic_settings.png
  - images/ic_osc_logo.png
  - images/ic_add_pics.png
  - images/ic_eye.png